# Setup
title:        Personalized Budget Coaching
tagline:      Empowering you to take control of your financial life
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Curt Nordhielm
  url:        http://budgetcoachcurt.com

navlinks:
  - ["Home", ""]
  - ["Philosophy", "philosophy.html"]
  - ["Budgeting", "budgeting.html"]
  - ["Debt Elimination", "debt-elimination.html"]
  - ["Financial Crisis", "financial-crisis.html"]
  - ["Real Estate", "real-estate.html"]
  - ["Wealth Building", "wealth-building.html"]
  - ["Blog", "blog/"]

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

gem:
  - jekyll-paginate

paginate: 20
paginate_path: "/blog/page:num/"

exclude:
  - vendor
  - Gemfile*
  - README.md
  - CNAME
