# Setup
title:        Personalized Budget Coaching
tagline:      Empowering you to take control of your financial life
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Curt Nordhielm
  url:        http://budgetcoachcurt.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

exclude:
  - vendor
  - Gemfile*
  - README.md
